#!/bin/sh
#
# Copyright (c) 2014 The Linux Foundation. All rights reserved.
# Copyright (C) 2011-2012 OpenWrt.org
#


. /lib/uboot-envtools.sh
. /lib/functions.sh

board=$(board_name)

ubootenv_mtdinfo () {
	UBOOTENV_PART=$(cat /proc/mtd | grep APPSBLENV)
	mtd_dev=$(echo $UBOOTENV_PART | awk '{print $1}' | sed 's/:$//')
	mtd_size=$(echo $UBOOTENV_PART | awk '{print "0x"$2}')
	mtd_erase=$(echo $UBOOTENV_PART | awk '{print "0x"$3}')
	nor_flash=$(find /sys/bus/spi/devices/*/mtd -name ${mtd_dev})

	if [ -z "$UBOOTENV_PART" ]; then
		mtd_dev=$(echo $(find_mmc_part "0:APPSBLENV") | sed 's/^.\{5\}//')
		if [ -n "$mtd_dev" ]; then
			EMMC_UBOOTENV_PART=$(cat /proc/partitions | grep $mtd_dev)
			#convert block to bytes
			emmc_ubootenv_size=`expr $(echo $EMMC_UBOOTENV_PART | awk '{print $3}') \* 1024`
			ubootenv_size=0x`printf "%x" $emmc_ubootenv_size`
		fi
		mtd_erase=""
	elif [ -n "$nor_flash" ]; then
		ubootenv_size=$mtd_size
		sectors=$(( $ubootenv_size / $mtd_erase ))
	else
		# size is fixed to 0x40000 in u-boot
		ubootenv_size=0x40000
		sectors=$(( $ubootenv_size / $mtd_erase ))
	fi

	echo /dev/$mtd_dev 0x0 $ubootenv_size $mtd_erase $sectors
}

validate_device_node() {
	config_get dev $1 dev
	if [ "$dev" != "$2" ] || [ ! -e /etc/fw_env.config ]; then
		rm /etc/config/ubootenv /etc/fw_env.config
		return;
	fi

	exit 0
}

[ -e /etc/config/ubootenv ] && {
	config_load ubootenv
	config_foreach validate_device_node ubootenv $(default_uboot_env)
}

touch /etc/config/ubootenv

case "$board" in
qcom,ipq8074-ap-hk01-c1 |\
qcom,ipq8074-ap-hk01-c2 |\
qcom,ipq8074-ap-hk01-c3 |\
qcom,ipq8074-ap-hk01-c4 |\
qcom,ipq8074-ap-hk01-c5 |\
qcom,ipq8074-ap-hk01-c6 |\
qcom,ipq8074-ap-hk02 |\
qcom,ipq8074-ap-hk06 |\
qcom,ipq8074-ap-hk07 |\
qcom,ipq8074-ap-hk08 |\
qcom,ipq8074-ap-hk09 |\
qcom,ipq8074-ap-hk10-c1 |\
qcom,ipq8074-ap-hk10-c2 |\
qcom,ipq8074-ap-hk11-c1 |\
qcom,ipq8074-ap-hk12 |\
qcom,ipq8074-ap-hk14 |\
qcom,ipq8074-db-hk01 |\
qcom,ipq8074-db-hk02)
	ubootenv_add_uci_config $(ubootenv_mtdinfo)
	;;
esac

config_load ubootenv
config_foreach ubootenv_add_app_config ubootenv

exit 0
