#!/bin/sh  /etc/rc.common
#
# Copyright (c) 2013 The Linux Foundation. All rights reserved.
#
# The shebang above has an extra space intentially to avoid having
# openwrt build scripts automatically enable this package starting
# at boot.

START=70

start() {

	irq_nss_rps=`grep -m3 nss /proc/interrupts | cut -d ':' -f 1 | taili -n1 | tr -d ' '`
	[ -n "$irq_nss_rps" ] && echo 2 > /proc/irq/$irq_nss_rps/smp_affinity

	# Enable NSS RPS
	sysctl -w dev.nss.general.rps=1 >/dev/null 2>/dev/null

}

