#!/bin/sh /etc/rc.common

START=20
STOP=90

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1

enable_elink_ipaddr() {
	local interface="$1"

	config_get type "$interface" type
	config_get elink_ipaddr "$interface" elink_ipaddr
	config_get elink_netmask "$interface" elink_netmask

	if [ "$type" = "bridge" ] && [ -n "$elink_ipaddr" ] && [ -n "$elink_netmask" ]; then
		ifconfig br-${interface}:0 $elink_ipaddr netmask $elink_netmask
	fi
}

start() {
	stop
	[ -e /proc/sys/kernel/core_pattern ] && {
		ulimit -c unlimited
		echo '/tmp/%e.%p.%s.%t.core' > /proc/sys/kernel/core_pattern
	}
	service_start /sbin/netifd

	setup_switch() { return 0; }

	include /lib/network
	setup_switch

	sleep 5

	/sbin/wifi down
	/sbin/wifi up

	config_load network
	config_foreach enable_elink_ipaddr interface
}

restart() {
	ifdown -a
	sleep 1
	start
}

shutdown() {
	ifdown -a
	stop
}

stop() {
	/sbin/wifi down
	service_stop /sbin/netifd
}

reload() {
	ubus call network reload
	/sbin/wifi down
	/sbin/wifi up
}
