#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2011 OpenWrt.org

START=40

start() {
	[ -c /dev/watchdog ] || return 1
	[ -x /sbin/watchdog ] || return 1
	service_start /sbin/watchdog -t 5 /dev/watchdog
	echo -1000 > /proc/$(pgrep watchdog)/oom_score_adj
}
stop() {
	service_stop /sbin/watchdog
}
