#!/bin/sh

# Copyright (c) 2014 The Linux Foundation. All rights reserved.

format_ext4() {
	partname="rootfs_data"
	emmcblock="$(find_mmc_part "$partname")"
	[ -e "$emmcblock" ] && mkfs.ext4 "$emmcblock"
}

boot_hook_add switch2jffs format_ext4
